name: API CI/CD Pipeline

on:
  push:
    paths:
      - 'api/*'
      - '.github/workflows/api-pipeline.yml'

jobs:
  build:
    uses: kaua-nasc/delivery-guard/.github/workflows/docker-build.yml@develop
    with:
      project_dir: api
      image_name: ${{ secrets.API_IMAGE_NAME }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  deploy:
    needs: build
    uses: kaua-nasc/delivery-guard/.github/workflows/deploy-vm.yml@develop
    with:
      image_name: ${{ secrets.API_IMAGE_NAME }}
      container_name: ${{ secrets.API_CONTAINER_NAME }}
      ports: ${{ secrets.API_PORT }}
      env_vars: ${{ secrets.ENV_VARS }}
    secrets:
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      VM_SSH_KNOWN_HOSTS: ${{ secrets.VM_SSH_KNOWN_HOSTS }}