name: Deploy to Server

on:
  push:
    branches: ["develop"]  # Só dispara no push para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/delivery-guard-api:latest ./api
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/delivery-guard-api:latest
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ Conectado ao servidor!"
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/delivery-guard-api:latest
            sudo docker stop minha-app || true
            sudo docker rm minha-app || true
            sudo docker run -d --name minha-app -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/delivery-guard-api:latest