name: Deploy API Project to Server

on:
  push:
    paths: 
      - api/**
      - deploy.yml
      - deploy-api.yml
    branches:
      - "master"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      folder: api
    secrets: inherit