name: Deploy Service to Server

on:
  push:
    paths: 
      - service/**
      - deploy.yml
      - deploy-service.yml
    branches: 
      - "develop"
      - "master"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      folder: service
      port: 3000:3000
    secrets: inherit