name: Publish & Deploy Docker container

on:
  push:
    branches: [ "main", develop ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-vm.yml
    secrets:
      API_IMAGE_NAME: ${{ secrets.API_IMAGE_NAME }}
      API_CONTAINER_NAME: ${{ secrets.API_CONTAINER_NAME }}
      API_PORT: ${{ secrets.API_PORT }}
      ENV_VARS: ${{ secrets.ENV_VARS }}
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}