name: Docker Deploy

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of Docker image to deploy'
        required: true
        type: string
      container_name:
        description: 'Name for the container in the VM'
        required: true
        type: string
      ports:
        description: 'Port mapping (host:container)'
        required: false
        type: string
        default: '80:80'
      env_vars:
        description: 'Environment variables (KEY=VALUE, separated by commas)'
        required: false
        type: string
        default: ''
    secrets:
      VM_SSH_HOST:
        required: true
      VM_SSH_USER:
        required: true
      VM_SSH_PRIVATE_KEY:
        required: true
      VM_SSH_KNOWN_HOSTS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.VM_SSH_KNOWN_HOSTS }}

      - name: Prepare environment variables
        id: env_vars
        run: |
          if [ -z "${{ inputs.env_vars }}" ]; then
            echo "env_flags=" >> $GITHUB_OUTPUT
          else
            IFS=',' read -ra VARS <<< "${{ inputs.env_vars }}"
            FLAGS=""
            for var in "${VARS[@]}"; do
              FLAGS+=" -e \"$var\""
            done
            echo "env_flags=${FLAGS}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} "
            docker pull docker.io/${{ inputs.image_name }}:latest &&
            docker stop ${{ inputs.container_name }} || true &&
            docker rm ${{ inputs.container_name }} || true &&
            docker run -d \
              --name ${{ inputs.container_name }} \
              -p ${{ inputs.ports }} \
              ${{ steps.env_vars.outputs.env_flags }} \
              docker.io/${{ inputs.image_name }}:latest
          "