name: Deploy to VM

on:
  workflow_call:
    secrets:
      API_IMAGE_NAME:
        required: true
      API_CONTAINER_NAME:
        required: true
      API_PORT:
        required: true
      ENV_VARS:
        required: false
      VM_SSH_HOST:
        required: true
      VM_SSH_USER:
        required: true
      VM_SSH_PRIVATE_KEY:
        required: true
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          echo "Host: ${{ secrets.VM_SSH_HOST }}"
          echo "User: ${{ secrets.VM_SSH_USER }}"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            fi
            echo "--- Pulling latest Docker image ---"
            docker pull ${{ secrets.API_IMAGE_NAME }}:latest
            echo "--- Stopping existing container ---"
            docker stop ${{ secrets.API_CONTAINER_NAME }} || true
            echo "--- Removing existing container ---"
            docker rm ${{ secrets.API_CONTAINER_NAME }} || true
            echo "--- Starting new container ---"
            docker run -d \
              --name ${{ secrets.API_CONTAINER_NAME }} \
              -p ${{ secrets.API_PORT }} \
              ${{ secrets.ENV_VARS }} \
              ${{ secrets.API_IMAGE_NAME }}:latest