name: Docker Deploy

on:
  workflow_call:
    secrets:
      API_CONTAINER_NAME:
        required: true
      API_PORT:
        required: true
      API_IMAGE_NAME:
        required: true
      ENV_VARS:
        required: false
      VM_SSH_HOST:
        required: true
      VM_SSH_USER:
        required: true
      VM_SSH_PRIVATE_KEY:
        required: true
      VM_SSH_KNOWN_HOSTS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.VM_SSH_KNOWN_HOSTS }}

      - name: Prepare environment variables
        id: env_vars
        run: |
          if [ -z "${{ secrets.ENV_VARS }}" ]; then
            echo "env_flags=" >> $GITHUB_OUTPUT
          else
            IFS=',' read -ra VARS <<< "${{ secrets.ENV_VARS }}"
            FLAGS=""
            for var in "${VARS[@]}"; do
              FLAGS+=" -e \"$var\""
            done
            echo "env_flags=${FLAGS}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_SSH_HOST }} "
            docker pull docker.io/${{ secrets.API_IMAGE_NAME }}:latest &&
            docker stop ${{ secrets.API_CONTAINER_NAME }} || true &&
            docker rm ${{ secrets.API_CONTAINER_NAME }} || true &&
            docker run -d \
              --name ${{ secrets.API_CONTAINER_NAME }} \
              -p ${{ secrets.API_PORT }} \
              ${{ steps.env_vars.outputs.env_flags }} \
              docker.io/${{ secrets.API_IMAGE_NAME }}:latest
          "