name: Deploy to Server

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      port:
        required: false
        type: string
        default: 80:80
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code - ${{ inputs.folder }}
        uses: actions/checkout@v4

      - name: Login to Docker Hub - ${{ inputs.folder }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image - ${{ inputs.folder }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}-${{ inputs.folder }}:latest ./${{ inputs.folder }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}-${{ inputs.folder }}:latest
        
      - name: Deploy via SSH - ${{ inputs.folder }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ Conectado ao servidor!"
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}-${{ inputs.folder }}:latest
            sudo docker stop ${{ secrets.IMAGE_NAME }}-${{ inputs.folder }} || true
            sudo docker rm ${{ secrets.IMAGE_NAME }}-${{ inputs.folder }} || true
            sudo docker run --env-file /opt/${{ secrets.IMAGE_NAME }}/${{ inputs.folder }}/.env -d --name ${{ secrets.IMAGE_NAME }}-${{ inputs.folder }} -p ${{ inputs.port }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}-${{ inputs.folder }}:latest
