name: Deploy API to Server

on:
  push:
    paths: 
      - api/**
      - api-workflow.yml
    branches: 
      - "develop"
      - "master"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      folder: api
    secrets: inherit